-- pg sql
CREATE TABLE IF NOT EXISTS demo.t_user
(
    id           INT GENERATED BY DEFAULT AS IDENTITY,
    username     VARCHAR(50) UNIQUE NOT NULL,
    password     VARCHAR(255)       NOT NULL,
    age          SMALLINT DEFAULT 0 CHECK (age BETWEEN 0 AND 150),
    sex          SMALLINT CHECK (sex IN (0, 1, 2)), -- 0:未知, 1:男, 2:女
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_id PRIMARY KEY (id),
    CONSTRAINT uk_t_user_username UNIQUE (username)
);
-- 时间范围查询索引
CREATE INDEX IF NOT EXISTS idx_t_user_created_at ON demo.t_user (created_at);


CREATE TABLE IF NOT EXISTS demo.t_order
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no        VARCHAR(64)    NOT NULL,
    user_id         INT            NOT NULL,
    total_amount    DECIMAL(15, 2) NOT NULL CHECK (total_amount >= 0),
    order_status    SMALLINT       NOT NULL CHECK (order_status IN (0, 1, 2, 3, 4, 5, 9)),
    pay_status      SMALLINT       NOT NULL CHECK (pay_status IN (0, 1, 2)),
    pay_method      SMALLINT CHECK (pay_method IN (1, 2, 3, 4)),
    pay_time        TIMESTAMPTZ,
    delivery_status SMALLINT CHECK (delivery_status IN (0, 1, 2, 3)),
    phone           VARCHAR(20)    NOT NULL,
    address         TEXT           NOT NULL,
    remark          TEXT,
    created_at      TIMESTAMPTZ    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_order_id PRIMARY KEY (id),
    CONSTRAINT uk_t_order_order_no UNIQUE (order_no)
);

COMMENT ON TABLE demo.t_order IS '订单主表';
COMMENT ON COLUMN demo.t_order.order_no IS '订单号';
COMMENT ON COLUMN demo.t_order.user_id IS '用户ID';
COMMENT ON COLUMN demo.t_order.order_status IS '订单状态: 0-待支付, 1-已支付, 2-已发货, 3-已收货, 4-已完成, 5-已取消, 9-已关闭';
COMMENT ON COLUMN demo.t_order.pay_status IS '支付状态: 0-未支付, 1-支付中, 2-已支付';
COMMENT ON COLUMN demo.t_order.pay_method IS '支付方式: 1-支付宝, 2-微信, 3-银行卡, 4-现金';
COMMENT ON COLUMN demo.t_order.pay_time IS '支付时间';
COMMENT ON COLUMN demo.t_order.delivery_status IS '发货状态: 0-未发货, 1-已发货, 2-运输中, 3-已签收';

INSERT INTO demo.t_user (username,"password",age,sex,created_at,updated_at) VALUES
    ('tom','123',15,1,'2025-11-08 06:12:56.598186+08','2025-11-08 06:12:56.598186+08');

INSERT INTO demo.t_order (order_no,user_id,total_amount,order_status,pay_status,pay_method,pay_time,delivery_status,phone,address,remark,created_at,updated_at) VALUES
    ('123456',1,102.36,1,1,1,NULL,1,'3587548741','番禺区市桥',NULL,'2025-11-08 06:14:33.876029+08','2025-11-08 06:14:33.876029+08');

INSERT INTO demo.t_order (order_no,user_id,total_amount,order_status,pay_status,pay_method,pay_time,delivery_status,phone,address,remark,created_at,updated_at) VALUES
    ('123457',1,12.36,1,1,1,NULL,1,'3587548741','北京市',NULL,NULL,NULL);

INSERT INTO demo.t_order (order_no,user_id,total_amount,order_status,pay_status,pay_method,pay_time,delivery_status,phone,address,remark) VALUES
    ('123458',1,1582.36,1,1,1,NULL,1,'3587548742','上海市',NULL);



